### ISSUE TITLE
Struktur Modularitea

### ISSUE THREAD

**Issue by rezafaizarahman** [tealinuxos/modularitea#5]
Halo, 

Lihat dari struktur Tea Module Installer kayanya data apps nya masih [hardcore ditulis di html](https://github.com/tealinuxos/tea-module-installer/blob/master/tpm.ign/index.html), ya?

Mengusulkan untuk struktur Modularitea, kalau bisa jadi betul-betul modular dong 😁  

![modularitea_struktur](https://cloud.githubusercontent.com/assets/1758606/21484378/f711a002-cbc3-11e6-91a6-43333a2e3324.png)

Nanti dibuat kaya gini

``` 
modularitea
    ├── atom
    │   ├── firefox-developer.atom
    │   │   ├── install
    │   │   └── package.json
    │   └── git.atom
    │       ├── install
    │       └── package.json
    └── modul
        └── FeWD.modul
            ├── install
            └── package.json
``` 

Jadi di folder atom ada folder dari tiap-tiap atom. Contoh di atas ada firefox developer (firefox-developer.atom) sama git (git.atom). Nanti di dalam masing-masing folder ada berkas install yang isinya script untuk download berkas sama package.json yang isinya semacam metadata gitu, kaya package.json nya di paket npm. 

Di folder modul ada folder dari tiap-tiap modul Contoh di atas ada Front-end Web Developer (FeWD.modul). Nanti di dalam masing-masing folder ada berkas install & package.json yang kurang lebih isinya sama dengan yang di atom. 

Imho, kalau strukturnya gini bakal memudahkan untuk penambahan atom maupun modul kedepannya. Jadi nggak usah banyak update di core appsnya.

Kurang lebih seperti itu, kira-kira gimana guys? Mari berdiskusi 😁

**Comment by dikyarga** [comment]
Iya Mas, itu codingannya _hardcore_ sekali :laughing: 
Ide bagus, Mas @rezafaizarahman 

Coba aku perlajari dulu konsep _install_ dan package.json nya npm, Mas. 
Kalo dari sisi bash / python-nya gimana @mnirfan ?

**Comment by dikyarga** [comment]
Oh ya, tadi pas pertama baca, aku rada salah paham dengan konsep Atom dan Atom (Code Editor) :rofl: 

Berarti nanti ada : 
``` 
modularitea
    ├── atom
        ├── atom.atom
               ├── install
               └── package.json
```
Kalo dari sisi _developer_ bisa di atas kok, tinggal kesepakatan _naming_ -nya aja. Nah, kira-kira pengguna bakal salah paham juga gak, ya ? Hehe

**Comment by rezafaizarahman** [comment]
Iya, itu penamaannya aja kok, Dik. Sebetulnya di dalam folder atom juga nggak harus ada namafolder.atom, bisa namafolder aja. Cuma untuk memudahkan.

**Comment by mnirfan** [comment]
+1. menarik sekali soal meta data terpisah seperti itu. belum pernah kepikiran seperti itu. nanti tak pikirkan dulu cara buatnya sambil melirik manager paket yang sudah ada.

**Comment by rezafaizarahman** [comment]
@mnirfan Sebetulnya konsep metadata seperti itu udah banyak dipakai. Kalau di pemaketan debian itu metadatanya ada di berkas control di dalem folder debian. Di sana kan ada kaya nama paketnya, siapa yg buat, dependensinya apa aja, dll gitu, Fan

**Comment by mnirfan** [comment]
sudah diterapkan. terima kasih atas segala masukannya mas @rezafaizarahman & lek @dikyarga
