### ISSUE TITLE
Backend developer hanya ada 2 paket

### ISSUE THREAD

**Issue by mnirfan** [tealinuxos/modularitea#7]
Mengapa backend developer hanya ada apache2 dan mongodb? bisa dijelaskan alasannya? atau mungkin disini ada definisi yang berbeda dengan saya tentang backend web developer?

**Comment by dikyarga** [comment]
Itu emang belum kita lengkapi aja @mnirfan 
Silahkan tambahin sesuai yang ada dibayanganmu, Fan.
